### ISSUE TITLE
run 100 cause error "list index out of range"

### ISSUE THREAD

**Issue by happyfire** [joonspk-research/generative_agents#12]
Hello,
I followed the readme guide, and run the map server and reverie. But when enter option "run 100", after a few seconds, it cause a error. I log the exception, it shows "list index out of range".

(python3912) G:\ai\generative_agents\reverie\backend_server>python reverie.py
Enter the name of the forked simulation: base_the_ville_isabella_maria_klaus
Enter the name of the new simulation: test-simulation
Note: The agents in this simulation package are computational
constructs powered by generative agents architecture and LLM. We
clarify that these agents lack human-like agency, consciousness,
and independent decision-making.
---
Enter option: run 100
Error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.closeai-asia.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
Enter option: run 100
Error: list index out of range
Enter option:

**Comment by happyfire** [comment]
And run 10 is OK

**Comment by YuehChuan** [comment]
same error here
![image](https://github.com/joonspk-research/generative_agents/assets/7314531/bbd5815d-6e65-49ff-a9ac-d846859ed25b)

**Comment by YuehChuan** [comment]
maybe the issue raise from running  out of mine api quota😂
![image](https://github.com/joonspk-research/generative_agents/assets/7314531/0d4fa2a8-a220-4505-a08a-9daed7657bad)

**Comment by PeachyTaozi** [comment]
兄弟问题解决了吗？是要用代理吗？

**Comment by happyfire** [comment]
It seems that is the problem of network connecting to call LLM api
