### ISSUE TITLE
OpenAI discontinuing text-davinci-002 and text-davinci-003. What could be a replacement for these two models? 

### ISSUE THREAD

**Issue by jgranda1999** [joonspk-research/generative_agents#133]
OpenAI announced that on January 4th, 2024, they will be discontinuing a few models including text-davinci-002 and text-davinci-003. Therefore, I wanted to ask everyone, what replacements could be used instead of text-davinci-002 and text-davinci-003? Thanks!

**Comment by Dozengame** [comment]
gpt-3.5-turbo-instruct

**Comment by jgranda1999** [comment]
> gpt-3.5-turbo-instruct

Would this replace both text-davinci-002 and text-davinci-003 or just one of them? Based on this article: https://blog.nextideatech.com/openai-gpt-3-5-turbo-instruct/ , it only replaces 003. Please let me know what you think!

**Comment by Dozengame** [comment]
![image](https://github.com/joonspk-research/generative_agents/assets/132629140/31722062-3aac-4220-95d5-e5fe35834d86)


https://platform.openai.com/docs/deprecations 

> > gpt-3.5-turbo-instruct
> 
> Would this replace both text-davinci-002 and text-davinci-003 or just one of them? Based on this article: https://blog.nextideatech.com/openai-gpt-3-5-turbo-instruct/ , it only replaces 003. Please let me know what you think!

**Comment by jgranda1999** [comment]
Thank you!
