### ISSUE TITLE
Inquiry about the Maximum Number of Agents

### ISSUE THREAD

**Issue by Yang011013** [joonspk-research/generative_agents#135]
Hello,

I have a question regarding the definition of agents in the repository. Am I allowed to define more than 25 agents? If so, what is the maximum limit?

Thank you for your assistance.

Best regards,

**Comment by 2642543078** [comment]
你可以一直加 加个自己的虚拟背景  限额那看你的自己的外部配置了

**Comment by Yang011013** [comment]
好的，谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月05日 16:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [joonspk-research/generative_agents] Inquiry about the Maximum Number of Agents (Issue #135) |

你可以一直加 加个自己的虚拟背景 限额那看你的自己的外部配置了
