### ISSUE TITLE
How to enable remote web access?

### ISSUE THREAD

**Issue by PiPi-happy** [joonspk-research/generative_agents#32]
Because I want to deploy the service on a cloud server for simulation, but currently the program is restricted to run only on localhost 127.0.0.1. So, how can I change it to 0.0.0.0?

**Comment by frankcarey** [comment]
frontend_server is actually a backend and frontend server via django, so you can set django ags like so in whatever "runner" you are using for cloud server.

`python manage.py runserver 0.0.0.0:8080`

**Comment by frankcarey** [comment]
The "backend_server" communicates with django (frontend_server) by simply reading and writing files to disk, so if you were to deploy this you would need to start the backend_server in another background process before you start the frontend server FYI.

**Comment by PiPi-happy** [comment]
> frontend_server is actually a backend and frontend server via django, so you can set django ags like so in whatever "runner" you are using for cloud server.
> 
> `python manage.py runserver 0.0.0.0:8080`

thank u
