### ISSUE TITLE
"movement/0.json" file did not generate properly.

### ISSUE THREAD

**Issue by HongyiLU** [joonspk-research/generative_agents#37]
After entering prompt "run 3", the demo has been working well until i got this error:

Klaus Mueller persona.scratch.importance_trigger_curr:: 145
150
aldhfoaf/????
the Ville:Dorm for Oak Hill College:Klaus Mueller's room:bed
Traceback (most recent call last):
  File "D:\generative_agents\reverie\backend_server\reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "D:\generative_agents\reverie\backend_server\reverie.py", line 401, in start_server
    with open(curr_move_file, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '../../environment/frontend_server/storage/test-simulation3/movement/0.json' 

Can anyone help me out of this pls?

**Comment by numbmelon** [comment]
check #2

**Comment by HongyiLU** [comment]
> check #2

thx, it works
