### ISSUE TITLE
Cython version?

### ISSUE THREAD

**Issue by tripathiarpan20** [joonspk-research/generative_agents#4]
Thanks for open-sourcing the implementation!

While installing the requirements with `pip install -r requirements.txt`, I am getting many build errors related to Cython, using a Windows 10 system.

Can you please share further instructions to setup?

**Comment by illmet** [comment]
I have the same issue too, on a Mac arm system. However, only specifying the Django version and removing the sklearn==0.0, it seemed to work for me. I've attached the requirements file that I've used.
[requirements.txt](https://github.com/joonspk-research/generative_agents/files/12306430/requirements.txt)

**Comment by tripathiarpan20** [comment]
Thanks!

Btw I tried on WSL 2 with virtual environment and the same series of steps worked.
