### ISSUE TITLE
unable to install click==8.0.3r==0.11.0

### ISSUE THREAD

**Issue by SeeWhysimon** [joonspk-research/generative_agents#53]
As listed in _requirements.txt_, we need to install _click==8.0.3r==0.11.0_, and I ran the command in the cmd but somehow it didn't work at all.

![屏幕截图 2023-08-12 135946](https://github.com/joonspk-research/generative_agents/assets/137471535/29d2dfbb-5dc6-45cb-b27d-b3f844427d61)

![屏幕截图 2023-08-12 135231](https://github.com/joonspk-research/generative_agents/assets/137471535/b8cd26a5-7a87-4e0e-9ade-c56cc9cabc8f)

Later I thought it might be the combination of two different files, so I input the command `pip install click==8.0.3` and `pip install r==0.11.0` respectively. Somehow the former one worked but not the second one.

![屏幕截图 2023-08-12 135231](https://github.com/joonspk-research/generative_agents/assets/137471535/ce24685e-ef5d-4c78-9879-a15500c7145d)

So what is the problem? Looking forward to the answer.

**Comment by Cdingram** [comment]
What version of python are you using? The instructions say they used 3.9.12, I used 3.9.1 and it worked fine for me.

**Comment by SeeWhysimon** [comment]
> What version of python are you using? The instructions say they used 3.9.12, I used 3.9.1 and it worked fine for me.

I figured out my problem. thx for the reply : )

**Comment by SeeWhysimon** [comment]
> What version of python are you using? The instructions say they used 3.9.12, I used 3.9.1 and it worked fine for me.

I figured out my problem. thx for the reply : )
