### ISSUE TITLE
Always stuck in during run step

### ISSUE THREAD

**Issue by ShadowTeamCN** [joonspk-research/generative_agents#66]
offcial settings in tutorials ,
run 10
and stuck in this step,
any idea about how to solve this?
![image](https://github.com/joonspk-research/generative_agents/assets/11573254/b574c3c9-8a5e-4c72-9633-2df360f88a9b)

**Comment by daigd5** [comment]
you can visit [http://localhost:8000/simulator_home](home)   page to continue the step

**Comment by Smilencelsy** [comment]
> you can visit [http://localhost:8000/simulator_home](home) page to continue the step

thanks for your help

**Comment by yz665** [comment]
> you can visit [http://localhost:8000/simulator_home](home) page to continue the step

It does't work with me, it stuck in the process persona.scratch.importance_triggger_curr: : 145 150.

**Comment by thulanxc** [comment]
they are sleeping in the first 2000 steps or more, be patient.

**Comment by nullwriter** [comment]
> they are sleeping in the first 2000 steps or more, be patient.

I'm having this issue too.
Do you mean if we run 3 steps, the first 2000 is just sleeping? That doesn't make sense

**Comment by ShadowTeamCN** [comment]
i find the root cause is I am using the society implement code to replace other none ChatGPT-turbo to ChatGPT-turbo API

**Comment by devpramod** [comment]
@ShadowTeamCN How did you solve this issue? Could you please help me out?

**Comment by MrKiing-Jin** [comment]
> 您可以访问 [http://localhost:8000/simulator_home ](home)页面继续该步骤

It really works！Thanks bro
